apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels: {app: myapp}
  template:
    metadata:
      labels: {app: myapp}
    spec:
      containers:
      - name: myapp
        image: ghcr.io/michael-angelok/devops-sndbx:84f6de585316004f9a141f2775ddbfdcecff5e02
        ports:
        - containerPort: 8080