name: ci
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install pytest
      - run: pytest test_app.py
      - run: pip install flake8
      - run: flake8 test_app.py

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
      
      - name: Build artefact
        run: |
          mkdir -p dist
          tar czf dist/myapp-linux-amd64.tar.gz app.py Dockerfile

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/myapp-linux-amd64.tar.gz
        if: startsWith(github.ref, 'refs/tags/')
        